name: Zephyrus
version: ${plugin.version}
description: Zephyrus is an all-in-one magic plugin providing magic spells and items that users can use on RPG and survival servers alike

author: minnymin3

main: com.minnymin.zephyrus.core.ZephyrusPlugin
load: STARTUP
website: http://dev.bukkit.org/bukkit-plugins/zephyrus/
